BEGIN:VCALENDAR
VERSION:2.0
<?php
    /**
     * CAUTION: this file depends on UNIX time stamps
     */

    $format = 'Ymd\THis';
?>
<?php foreach ($this->dates as $date) : ?>
BEGIN:VEVENT
<?php echo 'UID:' . $date->getDenominationId() . $date->getHolidayId() . $date->getStartDay() .'@ijew' . "\n"; ?>
<?php echo 'DTSTAMP:' . date($format) . "\n"; ?>
<?php echo 'SUMMARY:' . $date->getTitle() . "\n"; ?>
<?php echo 'DTSTART:' . date($format, $date->getStartStamp()) . "\n"; ?>
<?php echo 'DTEND:' . date($format, $date->getEndStamp()) . "\n"; ?>
END:VEVENT
<?php endforeach; ?>
END:VCALENDAR
