BEGIN:VCALENDAR
VERSION:2.0
<?php
    /**
     * CAUTION: this file depends on UNIX time stamps
     */

    $format = 'Ymd\THis';
    $dayFormat = 'Ymd';
?>
<?php foreach ($this->dates as $date) : ?>
BEGIN:VEVENT
<?= 'UID:' . $date->getDenominationId() . $date->getHolidayId() . $date->getStartDay() .'@ijew' . "\n"; ?>
<?= 'DTSTAMP:' . date($format) . "\n"; ?>
<?= 'SUMMARY:' . $date->getTitle() . "\n"; ?>
<?= 'DTSTART:' . date($dayFormat, $date->getStartStamp()) . "\n"; ?>
<?= 'DTEND:' . date($dayFormat, $date->getEndStamp()) . "\n"; ?>
END:VEVENT
<?php endforeach; ?>
END:VCALENDAR
